version: '3.7'


# build the hugo image
services:
  hugo:
    build:
      context: .
    volumes:
      - ".:/site"
    image: hugo:latest

  server:
    image: hugo:latest
    command: server --bind="0.0.0.0"
    volumes:
     - ".:/site"
    ports:
     - "80:1313"
    
